site_name: XBridgeX
copyright: Copyright &copy; 2020 - 2021 XBridgeX
nav:
    - HOME: index.md
    - 用户手册:
      - 主页: user/index.md
      - XBridgeN:
        - 概述: user/xbn/index.md
        - 开始使用: user/xbn/start.md
        - 一般配置: user/xbn/config.md
        - 高级配置: user/xbn/regex.md
      - XBridgeR:
        - 概述: user/xbr/index.md
        - 安装: user/xbr/install.md
        - 文件: user/xbr/files.md
        - 用户命令: user/xbr/user_cmd.md
        - 原生命令: user/xbr/native_cmd.md
        - 正则表达式: user/xbr/regex.md
        - websocket开发: user/xbr/wss.md
        - 常见问题: user/xbr/QandA.md
      - LLWebsocketR:
        - 安装: user/llws/install.md
      - Nillauncher:
        - 概述: user/nil/index.md
        - 启动参数: user/nil/start_arg.md
    - 开发手册:
      - 安装: dev/install.md
      - 搭建开发环境: dev/enviroment.md
      - 通信加密: dev/encrypt.md
      - 数据包: 
        - LLWebsocketR: dev/packs/llws.md
        - Nillauncher: dev/packs/nillauncher.md
    - 关于: about.md
theme:
    name: material
    language: zh
    logo: img/ico.svg
    favicon: img/favicon.png
    features:
        - search.highlight
        - seach.suggest
    plugins:
      - search:
          separator: '[\s\-\.]'

extra:
  generator: false

markdown_extensions:
  - pymdownx.critic
  - pymdownx.highlight
  - pymdownx.superfences